common/modules/slider/src/backend/models/UploadImage.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

namespace common\modules\slider\src\backend\models;

use Yii;
use yii\base\Model;
use yii\web\UploadedFile;

use common\modules\slider\src\common\helpers\File;
use common\modules\slider\src\common\helpers\Directory;

/**
 * Model class for uploading image
 *
 * @property UploadedFile $imageFile
 *
 * @author Vladimir Kuprienko <vldmr.kuprienko@gmail.com>
 */
class UploadImage extends Model
{
    /**
     * @var UploadedFile
     */
    public $imageFile;

    /**
     * @var string
     */
    protected $_imagesRoot;
    /**
     * @var string
     */
    protected $_imagePrefix;


    /**
     * @param string $imagesRoot
     * @param string $imagePrefix
     * @inheritdoc
     */
    public function __construct($imagesRoot, $imagePrefix, array $config = [])
    {
        $this->_imagesRoot = Yii::getAlias($imagesRoot);
        $this->_imagePrefix = $imagePrefix;

        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['imageFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, jpeg, gif']
        ];
    }

    /**
     * Method for generating unique image name
     *
     * @return string
     */
    protected function getImageName()
    {
        $fileName = File::getCrc32RandomName(
            $this->imageFile->baseName, $this->imageFile->extension, $this->_imagePrefix
        );

        if(Directory::isExists($this->_imagesRoot . '/' . $fileName)) {
            $this->getImageName();
        }

        return $fileName;
    }

    /**
     * Method for uploading the image to the server
     *
     * @return bool|string returns path to image if the file is saved successfully
     */
    public function upload()
    {
        if($this->validate()) {
            Directory::create($this->_imagesRoot, true);

            $fileName = $this->getImageName();
            $path = File::getPathToFile($this->_imagesRoot, $fileName);

            if($this->imageFile->saveAs($path)) {
                return File::getUrlToFile($path, "web");
            }
        }

        return false;
    }
}

common/modules/slider/src/backend/controllers/ContentController.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

namespace common\modules\slider\src\backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

use common\modules\slider\src\common\entities\SliderContent;
use common\modules\slider\src\backend\models\forms\AddHtml;
use common\modules\slider\src\backend\models\forms\AddImage;

/**
 * ContentController for SliderModule
 *
 * @author Vladimir Kuprienko <vldmr.kuprienko@gmail.com>
 */
class ContentController extends Controller
{
    /**
     * @var \common\modules\slider\src\backend\Module
     */
    public $module;


    /**
     * Render form for adding slider content
     *
     * @param AddHtml|AddImage $form
     * @param string $view
     * @param array $params
     * @return \yii\web\Response|string
     */
    public function renderForm($form, $view, $params = [])
    {
        if (Yii::$app->request->isPost) {
            $form->load(Yii::$app->request->post());
            if ($form->save()) {
                return $this->redirect(Yii::$app->request->referrer);
            }

            $params['errors'] = $form->getErrors();
        }

        return $this->render($view, $params);
    }

    /**
     * Add image to slider
     *
     * @param integer $sliderId
     * @return string|\yii\web\Response
     */
    public function actionAddImage($sliderId)
    {
        /** @var AddImage $addImageForm */
        $addImageForm = Yii::$container->get('AddImageModel');
        $addImageForm->sliderId = $sliderId;

        return $this->renderForm($addImageForm, 'add_image', [
            'addImageForm' => $addImageForm,
            'uploadImage' => Yii::$container->get('UploadImageModel')
        ]);
    }

    /**
     * Add HTML content to slider
     *
     * @param integer $sliderId
     * @return string|\yii\web\Response
     */
    public function actionAddHtml($sliderId)
    {
        $form = new AddHtml();
        $form->sliderId = $sliderId;

        return $this->renderForm($form, 'add_html', [
            'model' => $form
        ]);
    }

    /**
     *  Edit the slider content
     *
     * @param integer $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionEdit($id)
    {
        if(Yii::$app->request->isPost) {
            if ($sliderContent = SliderContent::findOne($id)) {
                $sliderContent->load(Yii::$app->request->post());
                $sliderContent->update();
            }

            return $this->redirect(Yii::$app->request->referrer);
        }

        throw new NotFoundHttpException("Page not found!");
    }

    /**
     * Delete the slider content
     *
     * @param integer $id
     * @return \yii\web\Response
     */
    public function actionDelete($id)
    {
        if ($sliderContent = SliderContent::findOne($id)) {
            $sliderContent->delete();
        }

        return $this->redirect(Yii::$app->request->referrer);
    }
}

common/modules/slider/src/backend/controllers/SliderController.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

namespace common\modules\slider\src\backend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;

use common\modules\slider\src\common\entities\Slider;

/**
 * SliderController for SliderModule
 *
 * @author Vladimir Kuprienko <vldmr.kuprienko@gmail.com>
 */
class SliderController extends Controller
{
    /**
     * @inheritdoc
     */
    public $defaultAction = "list";


    /**
     * Render list of sliders
     *
     * @return string
     */
    public function actionList()
    {
        $sliders = Slider::find()
            ->withSlides()
            ->all();

        return $this->render('list', [
            'sliders' => $sliders
        ]);
    }

    /**
     * Crate a slider
     *
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $slider = new Slider();

        if(Yii::$app->request->isPost) {
            $slider->load(Yii::$app->request->post());

            if($slider->insert()) {
                return $this->redirect(Url::toRoute('/slider'));
            }
        }

        return $this->render('create', [
            'slider' => $slider
        ]);
    }

    /**
     * Edit the slider
     *
     * @param integer $sliderId
     * @return string
     */
    public function actionEdit($sliderId)
    {
        $slider = Slider::find()
            ->where(['id' => $sliderId])
            ->withSlides(['position' => SORT_ASC])
            ->one();

        if(Yii::$app->request->isPost) {
            $slider->load(Yii::$app->request->post());
            $slider->update(false);
        }

        return $this->render('edit/edit', [
            'slider' => $slider
        ]);
    }

    /**
     * Delete the slider
     *
     * @param integer $sliderId
     * @return \yii\web\Response
     */
    public function actionDelete($sliderId)
    {
        if ($slider = Slider::findOne($sliderId)) {
            $slider->delete();
        }

        return $this->redirect(Yii::$app->request->referrer);
    }
}

common/modules/slider/src/backend/views/content/add_html.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

use common\modules\slider\src\common\entities\SliderContent;
use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use bl\ace\AceWidget;
use common\modules\slider\src\backend\widgets\Error;
use common\modules\slider\src\backend\Module as Slider;

/**
 * View file for Content controller
 *
 * @var \common\modules\slider\src\backend\models\forms\AddHtml $model
 * @var array $errors
 *
 * @author Vladimir Kuprienko <vldmr.kuprienko@gmail.com>
 */

\yii\bootstrap\BootstrapAsset::register($this);

$this->title = Slider::t('backend.content', 'Add HTML content');

$this->params['breadcrumbs'][] = [
    'label' => Slider::t('backend.breadcrumbs', 'Slider list'),
    'url' => ['/slider']
];
$this->params['breadcrumbs'][] = [
    'label' => Slider::t('backend.breadcrumbs', 'Edit slider'),
    'url' => ['slider/edit', 'sliderId' => $model->sliderId]
];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="box">

    <!--TITLE-->
    <div class="box-title">
        <h1>
            <?= FA::i(FA::_EDIT) . ' ' . $this->title; ?>
        </h1>

        <?= Html::a(
            Slider::t('backend.button', 'Cancel'),
            Url::toRoute(['/slider/slider/edit', 'sliderId' => $model->sliderId]),
            ['class' => 'btn btn-danger btn-xs']) ?>
    </div>

    <!--CONTENT-->
    <div class="box-content">

        <h1 class="text-center">
            <?= $this->title; ?>
        </h1>
        <div class="row">
            <div class="col-md-8 block-center">
                <?php if (!empty($errors)): ?>
                    <?= Error::widget(['errors' => $errors]) ?>
                <?php endif; ?>
                <?php $form = ActiveForm::begin([
                        'enableClientValidation' => false
                    ]) ?>
                    <?= $form->field($model, 'position')
                            ->input('number', [
                                'min' => 1,
                                'value' => SliderContent::find()->where(['slider_id' => $model->sliderId])->max('position') + 1
                            ]) ?>
                    <?= $form->field($model, 'content')->widget(AceWidget::className(), [
                        'enableEmmet' => true,
                        'attributes' => [
                            'style' => 'width: 100%; min-height: 400px;'
                        ]
                    ])->label(Slider::t('backend.content', 'HTML content')) ?>
                    <?= Html::submitButton(
                        Slider::t('backend.button', 'Add'),
                        [ 'class' => 'btn btn-success pull-right' ]
                    ) ?>
                <?php $form->end() ?>
            </div>
        </div>
    </div>
</div>

common/modules/slider/src/backend/views/content/add_image.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use common\modules\slider\src\backend\widgets\Error;
use common\modules\slider\src\backend\Module as Slider;
use common\modules\slider\src\backend\models\UploadImage;

/**
 * View file for Content controller
 *
 * @var \yii\web\View $this
 * @var \common\modules\slider\src\backend\models\forms\AddImage $addImageForm
 * @var UploadImage $uploadImage
 * @var array $errors
 *
 * @author Vladimir Kuprienko <vldmr.kuprienko@gmail.com>
 */

\yii\bootstrap\BootstrapAsset::register($this);

$this->title = Slider::t('backend.content', 'Add image');

$this->params['breadcrumbs'][] = [
    'label' => Slider::t('backend.breadcrumbs', 'Slider list'),
    'url' => ['/slider']
];
$this->params['breadcrumbs'][] = [
    'label' => Slider::t('backend.breadcrumbs', 'Edit slider'),
    'url' => ['slider/edit', 'sliderId' => $addImageForm->sliderId]
];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="box">

    <!--TITLE-->
    <div class="box-title">
        <h1>
            <?= FA::i(FA::_EDIT) . ' ' . $this->title; ?>
        </h1>

        <?= Html::a(
            Slider::t('backend.button', 'Cancel'),
            Url::toRoute(['/slider/slider/edit', 'sliderId' => $addImageForm->sliderId]),
            ['class' => 'btn btn-danger btn-xs']) ?>
    </div>

    <!--CONTENT-->
    <div class="box-content">

        <h1 class="text-center">
            <?= FA::i(FA::_EDIT) . ' ' . $this->title; ?>
        </h1>


        <div class="row">
            <div class="col-md-8 block-center">
                <?php if (!empty($errors)): ?>
                    <?= Error::widget(['errors' => $errors]) ?>
                <?php endif; ?>
                <?php $form = ActiveForm::begin([
                    'options' => ['enctype' => 'multipart/form-data'],
                    'enableClientValidation' => false
                ]) ?>
                    <?= $form->field($addImageForm, 'position')
                            ->input('number', [
                                'min' => 1
                            ]) ?>
                    <?= $form->field($addImageForm, 'content')
                            ->label(Slider::t('backend.content', 'Path to image file...')) ?>
                    <div class="form-group">
                        <?= $form->field($uploadImage, 'imageFile')
                                ->fileInput()
                                ->label(Slider::t('backend.content', 'or upload new file')) ?>
                    </div>
                    <?= $form->field($addImageForm, 'alt') ?>
                    <?= $form->field($addImageForm, 'params') ?>
                    <?= Html::submitButton(
                        Slider::t('backend.button', 'Add'),
                        [ 'class' => 'btn btn-success pull-right' ]
                    ) ?>
                <?php $form->end() ?>
            </div>
        </div>
    </div>
</div>

common/modules/slider/src/backend/views/slider/create.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use common\modules\slider\src\common\entities\Slider;
use common\modules\slider\src\backend\Module as SliderModule;

/**
 * View file for Slider controller
 *
 * @var Slider $slider
 *
 * @author Albert Gainutdinov <xalbert.einsteinx@gmail.com>
 */

\yii\bootstrap\BootstrapAsset::register($this);

$this->title = SliderModule::t('backend.create', 'Create slider');

$this->params['breadcrumbs'][] = [
    'label' => SliderModule::t('backend.breadcrumbs', 'Slider list'),
    'url' => ['/slider']
];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="box">

    <!--TITLE-->
    <div class="box-title">
        <h1>
            <?= FA::i(FA::_EDIT) . ' ' . $this->title; ?>
        </h1>

        <?= Html::a(
            FA::i(FA::_USER_PLUS) . SliderModule::t('backend.button', 'Cancel'),
            Url::toRoute(['/slider']),
            ['class' => 'btn btn-danger btn-xs']) ?>
    </div>

    <!--CONTENT-->
    <div class="box-content">


        <div class="row">
            <div class="col-md-8 block-center">
                <?php
                    /** @var ActiveForm $form */
                    $form = ActiveForm::begin()
                ?>
                    <?= $form->field($slider, 'key') ?>
                    <?= Html::submitButton(SliderModule::t('backend.buttoon', 'Create'), [
                        'class' => 'btn btn-success pull-right'
                    ]) ?>
                <?php $form->end() ?>
            </div>
        </div>
    </div>
</div>

common/modules/slider/src/backend/views/slider/edit/_content.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use bl\ace\AceWidget;
use common\modules\slider\src\common\entities\SliderContent;
use common\modules\slider\src\backend\Module as Slider;

/**
 * View file for Slider controller
 *
 * @var SliderContent[] $content
 *
 * @author Albert Gainutdinov <xalbert.einsteinx@gmail.com>
 */

\yii\bootstrap\BootstrapPluginAsset::register($this);
?>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
<?php foreach ($content as $number => $slide): ?>
    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading-<?= $number ?>">
            <h4 class="panel-title">
                <a role="button"
                   data-toggle="collapse"
                   data-parent="#accordion"
                   href="#collapse-<?= $number ?>"
                   aria-expanded="true"
                   aria-controls="collapse-<?= $number ?>">
                    <?= sprintf("%s #%d",
                        Slider::t('backend.edit', 'Slide'),
                        $number + 1)  ?>
                </a>
                <?= Html::a(
                    Slider::t('backend.button', 'Delete'),
                    Url::toRoute([
                        '/slider/content/delete',
                        'id' => $slide->id
                    ]),
                    ['class' => 'text-danger pull-right']
                ) ?>
            </h4>
        </div>
        <div id="collapse-<?= $number ?>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<?= $number ?>">
            <div class="panel-body">
                <?php
                    /** @var ActiveForm $form */
                    $form = ActiveForm::begin([
                        'action' => ["/slider/content/edit", 'id' => $slide->id]
                    ])
                ?>
                    <?= $form->field($slide, 'position')
                            ->input('number', [
                                'min' => 1
                            ]) ?>
                    <div class="form-group">
                        <?php if($slide->is_image): ?>
                            <?= $form->field($slide, 'alt') ?>
                            <?= $form->field($slide, 'params')
                                ->label(Slider::t('backend.edit', 'Params')) ?>
                            <?= Html::img($slide->content, [
                                'class' => 'img-thumbnail',
                                'style' => 'width: 100%;'
                            ]) ?>
                        <?php else: ?>
                            <?= $form->field($slide, 'content')
                                ->widget(AceWidget::className(), [
                                    'enableEmmet' => true,
                                    'attributes' => [
                                        'style' => 'width: 100%; min-height: 400px;'
                                    ]
                                ])
                                ->label(Slider::t('backend.edit', 'HTML content')) ?>
                        <?php endif; ?>
                    </div>
                    <?= Html::submitButton(
                        Slider::t('backend.button', 'Save changes'),
                        [ 'class' => 'btn btn-success pull-right' ]
                    ) ?>
                <?php $form->end() ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>
</div>

common/modules/slider/src/backend/views/slider/edit/edit.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

use common\modules\slider\src\common\entities\Slider;
use common\modules\slider\src\backend\Module as SliderModule;

/**
 * View file for Slider controller
 *
 * @var Slider $slider
 *
 * @author Albert Gainutdinov <xalbert.einsteinx@gmail.com>
 */

\yii\bootstrap\BootstrapAsset::register($this);

$this->title = SliderModule::t('backend.breadcrumbs', 'Edit slider');

$this->params['breadcrumbs'][] = [
    'label' => SliderModule::t('backend.breadcrumbs', 'Slider list'),
    'url' => ['/slider']
];
$this->params['breadcrumbs'][] = $this->title;
?>


<div class="box">

    <!--TITLE-->
    <div class="box-title">
        <h1>
            <?= FA::i(FA::_EDIT) . ' ' . $this->title; ?>
        </h1>

        <?= Html::a(
            SliderModule::t('backend.button', 'Cancel'),
            Url::toRoute(['/slider']),
            ['class' => 'btn btn-danger btn-xs']) ?>
    </div>

    <!--CONTENT-->
    <div class="box-content">

        <h1 class="text-center">
            <?= $this->title; ?>
        </h1>
        <div class="row">
            <div class="col-md-8 block-center">
                <?php
                    /** @var ActiveForm $form */
                    $form = ActiveForm::begin([
                        'enableClientValidation' => false
                    ])
                ?>
                    <?= $form->field($slider, 'key') ?>
                    <?= Html::submitButton(
                        SliderModule::t('backend.button', 'Save'),
                        [ 'class' => 'btn btn-success' ]
                    ) ?>
                <?php $form->end() ?>


                <h2 class="text-center">
                    <?= SliderModule::t('backend.edit', 'Slides') ?>
                </h2>
                <div>
                    <?= Html::a(SliderModule::t('backend.button', 'Add HTML content'),
                        Url::toRoute([
                            '/slider/content/add-html',
                            'sliderId' => $slider->id
                        ]),
                        [ 'class' => 'btn btn-success btn-xs pull-right' ]) ?>
                    <?= Html::a(SliderModule::t('backend.button', 'Add image'),
                        Url::toRoute([
                            '/slider/content/add-image',
                            'sliderId' => $slider->id
                        ]),
                        [ 'class' => 'btn btn-success btn-xs pull-right' ]) ?>
                </div>

                <br>
                <br>

                <?= $this->render('_content', [
                    'content' => $slider->sliderContent
                ]) ?>
            </div>
        </div>
    </div>
</div>

common/modules/slider/src/backend/views/slider/list.php
<?php
/**
 * @link https://github.com/black-lamp/yii2-slider
 * @copyright Copyright (c) Vladimir Kuprienko
 * @license BSD 3-Clause License
 */

use rmrevin\yii\fontawesome\FA;
use yii\helpers\Html;
use yii\helpers\Url;

use common\modules\slider\src\common\entities\Slider;
use common\modules\slider\src\backend\Module as SliderModule;

/**
 * View file for Slider controller
 *
 * @var Slider[] $sliders
 * @var array $slides
 *
 * @author Albert Gainutdinov <xalbert.einsteinx@gmail.com>
 */

\yii\bootstrap\BootstrapAsset::register($this);

$this->title = SliderModule::t('backend.breadcrumbs', 'Slider list');
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="box">

    <!--TITLE-->
    <div class="box-title">
        <h1>
            <?= FA::i(FA::_NAVICON) . ' ' . $this->title; ?>
        </h1>

        <?= Html::a(
            FA::i(FA::_USER_PLUS) . SliderModule::t('backend.button', 'Create slider'),
            Url::toRoute('create'),
            ['class' => 'btn btn-primary btn-xs']) ?>
    </div>

    <!--CONTENT-->
    <div class="box-content">

        <h1 class="text-center">
            <?= SliderModule::t('backend.list', 'Sliders list') ?>
        </h1>
        <div class="row">
            <div class="col-md-8 block-center">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>
                            <?= SliderModule::t('backend.list', 'Key') ?>
                        </th>
                        <th>
                            <?= SliderModule::t('backend.list', 'Slides count') ?>
                        </th>
                        <th>
                            <?= SliderModule::t('backend.list', 'Actions') ?>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($sliders as $number => $slider): ?>
                        <tr>
                            <td>
                                <?= ++$number ?>
                            </td>
                            <td>
                                <?= Html::a($slider->key,
                                    Url::toRoute([
                                        'slider/edit',
                                        'sliderId' => $slider->id
                                    ]),
                                    ['class' => 'text-center']) ?>
                            </td>
                            <td>
                                <?= count($slider->sliderContent) ?>
                            </td>
                            <td>
                                <?= Html::a(SliderModule::t('backend.button', 'Edit'),
                                    Url::toRoute([
                                        'slider/edit',
                                        'sliderId' => $slider->id
                                    ]),
                                    ['class' => 'btn btn-xs btn-warning']) ?>
                                <?= Html::a(SliderModule::t('backend.button', 'Delete'),
                                    Url::toRoute([
                                        'slider/delete',
                                        'sliderId' => $slider->id
                                    ]),
                                    ['class' => 'btn btn-xs btn-danger']) ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>